### ISSUE TITLE
CCF (V2) and ObjTree makes AHK V2 crash ...

### ISSUE THREAD

**Issue by hoppfrosch** [maul-esel/COM-Classes#46]
After the bugfix (http://www.autohotkey.com/forum/viewtopic.php?p=517398#517398) , which allows using ObjTree (http://http://www.autohotkey.com/forum/viewtopic.php?t=69756) to display objects from CCF, still one fatal error exists:

At the end of the following example program, AHK2 crashes and pops up a window (german OS): "Autohotkey_L funktioniert nicht mehr".

``` autohotkey
#SingleInstance
#include ..\..\_CCF_Error_Handler_.ahk
#include ..\..\CCFramework.ahk
#Include ..\..\Unknown\Unknown.ahk
#Include ..\..\ShellItem\ShellItem.ahk
#Include ..\..\Constant Classes\SIGDN.ahk
#Include ..\..\Constant Classes\SFGAO.ahk
#Include ..\..\Constant Classes\KNOWNFOLDERID.ahk


; #############################################
; Explicit filepath
shItem := ShellItem.FromAbsolutePath(A_AhkPath)

ObjTree(shItem)

; display a few names
MsgBox % "NORMALDISPLAY: <" shItem.GetDisplayName() ">`nFILESYSPATH: <" shItem.GetDisplayName(SIGDN.FILESYSPATH) ">`nDESKTOPABSOLUTEEDITING: <" shItem.GetDisplayName(SIGDN.DESKTOPABSOLUTEEDITING) ">`nPARENTRELATIVEFORADDRESSBAR: <" shItem.GetDisplayName(SIGDN.PARENTRELATIVEFORADDRESSBAR) ">"

; checking some attributes
ret := shItem.GetAttributes((SFGAO.HASPROPSHEET | SFGAO.ENCRYPTED | SFGAO.FOLDER | SFGAO.BROWSABLE), bits)
; to display wheter the flag is set or not, we use Utility function - or some bitwise operations
MsgBox % "HASPROPSHEET: <" CCFramework.HasEnumFlag(bits, SFGAO.HASPROPSHEET) ">`nENCRYPTED: <" CCFramework.HasEnumFlag(bits,SFGAO.ENCRYPTED) ">`nFOLDER: <" ((bits & SFGAO.FOLDER) > 0) ">`nBROWSABLE: <" ((bits & SFGAO.BROWSABLE) > 0) ">" 
```

I'm not quite sure, who's the culprit (either CCF, ObjTree, or AHK itself) - but it's beyond my capability to identify it ...

**Comment by maul-esel** [comment]
Sorry I can not confirm this on my system.
64bit again?

**Comment by hoppfrosch** [comment]
Yes ... 

System info:
AHK 2.0-a032-64bit
Win7SP1-64bit

**Comment by maul-esel** [comment]
Could you test if the latest change fixes this?

**Comment by hoppfrosch** [comment]
No success - same error occurs. :-(

**Comment by maul-esel** [comment]
Sorry, I forgot ObjTree did not support this at that time. Although there's only a little chance, check it out with [the new ObjTree](http://www.autohotkey.com/forum/viewtopic.php?p=517958#517958) version, please.

**Comment by hoppfrosch** [comment]
After Update of ObjTree to Version from 01.03.2012  everything works as expected - no crash of AHK at program end ...

Issue fixed -> CLOSED
